"""Generate the self-contained Kaggle notebook from the real source files.

The notebook must run on Kaggle without access to this private repo, so the
project's own modules are embedded into it. Embedding by hand would drift out
of sync with the sources the moment either changes, so it is generated instead:
re-run this script after touching unet.py / grid.py and the notebook is current
again.

    python isih/kaggle/make_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = Path(__file__).parent / "isih_train.ipynb"

EMBED = {
    "unet.py": REPO / "models" / "sic_correction" / "unet.py",
    "grid.py": REPO / "isih" / "grid.py",
}


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


def build_embed_cell() -> str:
    parts = [
        "# Project modules, embedded from the repo so this notebook runs standalone.",
        "# Generated by isih/kaggle/make_notebook.py -- do not edit here, edit the",
        "# source files and regenerate, otherwise the two silently diverge.",
        "from pathlib import Path",
        "Path('isih_src').mkdir(exist_ok=True)",
        "",
    ]
    for name, path in EMBED.items():
        source = path.read_text()
        parts.append(f"# ---- {name} " + "-" * (60 - len(name)))
        parts.append(f"Path('isih_src/{name}').write_text('''{source.replace(chr(92), chr(92) * 2).replace(chr(39) * 3, chr(92) + chr(39) * 3)}''')")
        parts.append("")
    parts.append("import sys; sys.path.insert(0, 'isih_src')")
    parts.append("print('modules written:', sorted(p.name for p in Path('isih_src').glob('*.py')))")
    return "\n".join(parts)


NOTEBOOK_INTRO = """# ISIH Prototype — Sea-Ice Bias-Correction Model

**This trains the Sept 8 ISIH prototype, not the December production model.**
See `isih/README.md` in the repo for the difference.

What this does: learns to correct the GLORYS12 ocean-reanalysis sea-ice field
toward what satellites actually observed (NOAA/NSIDC CDR).

    corrected = clip(background + model_correction, 0, 1)

The model predicts the *correction*, never the field, so an untrained model
reproduces the background exactly and can't be much worse than it.

### Before running

1. **Enable internet**: Notebook settings → Internet → On
2. **Enable GPU**: Notebook settings → Accelerator → GPU T4 x2
3. **Add CMEMS credentials** as Kaggle Secrets (Add-ons → Secrets):
   - `CMEMS_USERNAME`
   - `CMEMS_PASSWORD`

   These are the same Copernicus Marine credentials used in the repo's GitHub
   Actions. NSIDC needs no credentials at all.
"""


def main() -> int:
    cells = [
        md(NOTEBOOK_INTRO),
        md("## 1. Environment"),
        code(
            "!pip install -q copernicusmarine pyproj xarray netCDF4\n"
            "\n"
            "import torch\n"
            "print('torch', torch.__version__)\n"
            "print('CUDA available:', torch.cuda.is_available())\n"
            "if torch.cuda.is_available():\n"
            "    print('GPU:', torch.cuda.get_device_name(0))\n"
            "else:\n"
            "    print('WARNING: no GPU. Enable it in Notebook settings, or training will be ~20x slower.')"
        ),
        md("## 2. Project modules"),
        code(build_embed_cell()),
        md(
            "## 3. Credentials\n\n"
            "Read from Kaggle Secrets — never typed into a cell, so they are not "
            "saved into the notebook or its outputs."
        ),
        code(
            "import os\n"
            "from kaggle_secrets import UserSecretsClient\n"
            "\n"
            "secrets = UserSecretsClient()\n"
            "os.environ['COPERNICUSMARINE_SERVICE_USERNAME'] = secrets.get_secret('CMEMS_USERNAME')\n"
            "os.environ['COPERNICUSMARINE_SERVICE_PASSWORD'] = secrets.get_secret('CMEMS_PASSWORD')\n"
            "print('CMEMS credentials loaded from Kaggle Secrets')"
        ),
        md(
            "## 4. Download the truth field (NSIDC)\n\n"
            "No authentication needed. ~350 KB/day; one year is ~130 MB."
        ),
        code(
            "import urllib.request, concurrent.futures, re\n"
            "from pathlib import Path\n"
            "\n"
            "YEARS = [2019, 2020]   # prototype scope; widen for the production model\n"
            "BASE = 'https://noaadata.apps.nsidc.org/NOAA/G02202_V6/south/daily'\n"
            "nsidc_dir = Path('data/nsidc'); nsidc_dir.mkdir(parents=True, exist_ok=True)\n"
            "\n"
            "def year_files(year):\n"
            "    with urllib.request.urlopen(f'{BASE}/{year}/', timeout=60) as r:\n"
            "        html = r.read().decode('utf-8', 'replace')\n"
            "    return sorted(set(re.findall(r'href=\"(sic_pss25_[^\"]+\\.nc)\"', html)))\n"
            "\n"
            "def fetch(year, name):\n"
            "    dest = nsidc_dir / name\n"
            "    if dest.exists() and dest.stat().st_size > 1000:\n"
            "        return True\n"
            "    urllib.request.urlretrieve(f'{BASE}/{year}/{name}', dest)\n"
            "    return True\n"
            "\n"
            "jobs = [(y, n) for y in YEARS for n in year_files(y)]\n"
            "print(f'{len(jobs)} files to fetch')\n"
            "with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:\n"
            "    list(pool.map(lambda a: fetch(*a), jobs))\n"
            "print('downloaded:', len(list(nsidc_dir.glob('*.nc'))), 'files')"
        ),
        md(
            "## 5. Download the background field (GLORYS12) and build training pairs\n\n"
            "GLORYS12 is regridded onto the NSIDC grid by area-averaging — the truth "
            "field is never resampled, since resampling what you score against creates "
            "ice-edge artifacts indistinguishable from real model error."
        ),
        code(
            "import numpy as np, xarray as xr, copernicusmarine\n"
            "from grid import GlorysToNsidcRegridder\n"
            "\n"
            "GLORYS = 'cmems_mod_glo_phy_my_0.083deg_P1D-m'\n"
            "CORRIDOR = dict(min_lon=-5.0, max_lon=85.0, min_lat=-80.0, max_lat=-48.0)\n"
            "gl_dir = Path('data/glorys'); gl_dir.mkdir(parents=True, exist_ok=True)\n"
            "\n"
            "for year in YEARS:\n"
            "    target = gl_dir / f'glorys_{year}.nc'\n"
            "    if target.exists():\n"
            "        print(year, 'already downloaded'); continue\n"
            "    copernicusmarine.subset(\n"
            "        dataset_id=GLORYS, variables=['siconc'],\n"
            "        start_datetime=f'{year}-01-01T00:00:00', end_datetime=f'{year}-12-31T00:00:00',\n"
            "        minimum_longitude=CORRIDOR['min_lon'], maximum_longitude=CORRIDOR['max_lon'],\n"
            "        minimum_latitude=CORRIDOR['min_lat'], maximum_latitude=CORRIDOR['max_lat'],\n"
            "        output_directory=str(gl_dir), output_filename=target.name, overwrite=True)\n"
            "    print(year, 'done:', target.stat().st_size/1e6, 'MB')"
        ),
        code(
            "def load_nsidc_year(year):\n"
            "    files = sorted(nsidc_dir.glob(f'sic_pss25_{year}*.nc'))\n"
            "    truth, dates = [], []\n"
            "    template = xr.open_dataset(files[0])\n"
            "    for p in files:\n"
            "        with xr.open_dataset(p) as ds:\n"
            "            v = ds['cdr_seaice_conc'].isel(time=0).values.astype(np.float32)\n"
            "            truth.append(np.where((v >= 0) & (v <= 1), v, np.nan))\n"
            "            dates.append(int(p.name.split('_')[2]))\n"
            "    return np.stack(truth), np.asarray(dates, np.int32), template\n"
            "\n"
            "backgrounds, truths, masks, all_dates = [], [], [], []\n"
            "for year in YEARS:\n"
            "    truth, dates, template = load_nsidc_year(year)\n"
            "    gl = xr.open_dataset(gl_dir / f'glorys_{year}.nc')\n"
            "    rg = GlorysToNsidcRegridder(template, gl['latitude'].values, gl['longitude'].values)\n"
            "    print(f'{year}: corridor covers {rg.coverage()*100:.1f}% of the NSIDC grid')\n"
            "    gl_dates = np.array([int(s.replace('-','')) for s in\n"
            "                         gl['time'].dt.strftime('%Y-%m-%d').values], np.int32)\n"
            "    common, ni, gi = np.intersect1d(dates, gl_dates, return_indices=True)\n"
            "    bg = np.stack([rg(gl['siconc'].isel(time=int(i)).values.astype(np.float32)) for i in gi])\n"
            "    tr = truth[ni]\n"
            "    backgrounds.append(bg); truths.append(tr)\n"
            "    masks.append(np.isfinite(bg) & np.isfinite(tr)); all_dates.append(common)\n"
            "    print(f'  {len(common)} paired days')\n"
            "\n"
            "background = np.nan_to_num(np.concatenate(backgrounds), nan=0.0).astype(np.float32)\n"
            "truth = np.nan_to_num(np.concatenate(truths), nan=0.0).astype(np.float32)\n"
            "valid = np.concatenate(masks)\n"
            "dates = np.concatenate(all_dates)\n"
            "print('dataset:', background.shape, '| valid cells:', f'{valid.mean()*100:.1f}%')"
        ),
        md(
            "## 6. Sanity check the pairing\n\n"
            "Before training anything, confirm the two fields actually describe the same "
            "ocean. If background and truth were misaligned, correlation would be near "
            "zero and every later number would be meaningless."
        ),
        code(
            "v = valid\n"
            "corr = np.corrcoef(background[v], truth[v])[0, 1]\n"
            "bias = float((background[v] - truth[v]).mean())\n"
            "rmse = float(np.sqrt(((background[v] - truth[v])**2).mean()))\n"
            "print(f'correlation background vs truth : {corr:.3f}')\n"
            "print(f'mean bias (background - truth)   : {bias:+.4f}')\n"
            "print(f'background RMSE vs truth         : {rmse:.4f}   <-- the bar to beat')\n"
            "assert corr > 0.5, 'FIELDS ARE MISALIGNED — do not train on this'\n"
            "print"
            "('\\nAlignment OK. The trained model must beat the background RMSE above.')"
        ),
        md(
            "## 7. Train\n\n"
            "Temporal split — the last 20% of days is held out. A random split would "
            "leak adjacent days (ice fields are highly autocorrelated day to day) and "
            "inflate the score into meaninglessness."
        ),
        code(
            "import torch, torch.nn as nn\n"
            "from torch.utils.data import TensorDataset, DataLoader\n"
            "from unet import SICCorrectionUNet, apply_correction, count_parameters\n"
            "\n"
            "order = np.argsort(dates)\n"
            "background, truth, valid = background[order], truth[order], valid[order]\n"
            "split = int(len(background) * 0.8)\n"
            "print(f'train: {split} days | held-out: {len(background)-split} days')\n"
            "\n"
            "def make_loader(sl, shuffle):\n"
            "    x = torch.from_numpy(background[sl]).unsqueeze(1)\n"
            "    y = torch.from_numpy(truth[sl]).unsqueeze(1)\n"
            "    m = torch.from_numpy(valid[sl]).unsqueeze(1)\n"
            "    return DataLoader(TensorDataset(x, y, m), batch_size=8, shuffle=shuffle)\n"
            "\n"
            "train_loader = make_loader(slice(0, split), True)\n"
            "val_loader   = make_loader(slice(split, None), False)\n"
            "\n"
            "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
            "# Prototype: 1 input channel (the background field) and a small network.\n"
            "# The production model uses 19 channels -- see ML_ARCHITECTURE.md 1.2.\n"
            "model = SICCorrectionUNet(in_channels=1, base_filters=16, depth=3).to(device)\n"
            "print('parameters:', f'{count_parameters(model):,}')\n"
            "\n"
            "opt = torch.optim.Adam(model.parameters(), lr=1e-3)\n"
            "scaler = torch.cuda.amp.GradScaler(enabled=(device=='cuda'))\n"
            "\n"
            "def masked_mse(pred, target, mask):\n"
            "    d = ((pred - target) ** 2) * mask\n"
            "    return d.sum() / mask.sum().clamp(min=1)\n"
            "\n"
            "EPOCHS = 30\n"
            "best = float('inf')\n"
            "for epoch in range(1, EPOCHS + 1):\n"
            "    model.train()\n"
            "    for xb, yb, mb in train_loader:\n"
            "        xb, yb, mb = xb.to(device), yb.to(device), mb.to(device)\n"
            "        opt.zero_grad(set_to_none=True)\n"
            "        with torch.cuda.amp.autocast(enabled=(device=='cuda')):\n"
            "            corrected = apply_correction(xb, model(xb))\n"
            "            loss = masked_mse(corrected, yb, mb)\n"
            "        scaler.scale(loss).backward(); scaler.step(opt); scaler.update()\n"
            "\n"
            "    model.eval()\n"
            "    se = n = base_se = 0.0\n"
            "    with torch.no_grad():\n"
            "        for xb, yb, mb in val_loader:\n"
            "            xb, yb, mb = xb.to(device), yb.to(device), mb.to(device)\n"
            "            corrected = apply_correction(xb, model(xb))\n"
            "            se += (((corrected - yb)**2) * mb).sum().item()\n"
            "            base_se += (((xb - yb)**2) * mb).sum().item()\n"
            "            n += mb.sum().item()\n"
            "    rmse_model, rmse_base = (se/n)**0.5, (base_se/n)**0.5\n"
            "    skill = (1 - rmse_model/rmse_base) * 100\n"
            "    flag = ''\n"
            "    if rmse_model < best:\n"
            "        best = rmse_model; torch.save(model.state_dict(), 'isih_prototype.pt'); flag = ' *saved*'\n"
            "    print(f'epoch {epoch:2d}  model RMSE {rmse_model:.4f}  background {rmse_base:.4f}  '\n"
            "          f'improvement {skill:+.1f}%{flag}')"
        ),
        md(
            "## 8. Result\n\n"
            "The number that matters: does the model beat the background it corrects? "
            "If improvement is not positive, the honest outcome is to report that and "
            "ship the raw background — which is exactly the fallback the architecture "
            "already specifies."
        ),
        code(
            "# weights_only=True: this file holds tensors only, and the flag keeps\n"
            "# torch from unpickling arbitrary objects.\n"
            "model.load_state_dict(torch.load('isih_prototype.pt', weights_only=True))\n"
            "model.eval()\n"
            "se = base_se = n = 0.0\n"
            "with torch.no_grad():\n"
            "    for xb, yb, mb in val_loader:\n"
            "        xb, yb, mb = xb.to(device), yb.to(device), mb.to(device)\n"
            "        corrected = apply_correction(xb, model(xb))\n"
            "        se += (((corrected - yb)**2) * mb).sum().item()\n"
            "        base_se += (((xb - yb)**2) * mb).sum().item()\n"
            "        n += mb.sum().item()\n"
            "rmse_model, rmse_base = (se/n)**0.5, (base_se/n)**0.5\n"
            "print(f'held-out background RMSE : {rmse_base:.4f}')\n"
            "print(f'held-out model RMSE      : {rmse_model:.4f}')\n"
            "print(f'improvement              : {(1-rmse_model/rmse_base)*100:+.1f}%')\n"
            "print()\n"
            "if rmse_model < rmse_base:\n"
            "    print('Model beats its background on held-out data. Download isih_prototype.pt')\n"
            "else:\n"
            "    print('Model does NOT beat the background. Report this honestly and use the')\n"
            "    print('raw background for the demo -- that is the specified fallback, not a failure.')"
        ),
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
            "accelerator": "GPU",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    OUT.write_text(json.dumps(notebook, indent=1))
    print(f"wrote {OUT} ({OUT.stat().st_size / 1000:.0f} KB, {len(cells)} cells)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
